### ISSUE TITLE
Licensing is unclear: any GPL version?

### ISSUE THREAD

**Issue by puiterwijk** [taw/jrpg#8]
Please note that currently the README.txt says that the source code is GPL.

You are not mentioning a version, which means that anyone can use it under whatever version of the GPL they so desire.
It might be useful to mention which version of the GPL you intended ("GNU GPLv2 or later" for example).
Please note that the GPLv1 is not compatible with GPLv2 or later, so using that would not be my advice.

It would also be useful to put a COPYING statement in for people that want to package this for Linux distributions.

**Comment by taw** [comment]
If you have any specific GPL version in mind, feel free to treat it as also licensed under it, I'm really not that much into legalese. I don't even remember why I put GPL there instead of something simpler, but let's just make it what README says - any GPL version.

Third party files (backgrounds etc.) are under licences as described.

**Comment by taw** [comment]
I'll just close this unless there's a need for more clarification.

**Comment by puiterwijk** [comment]
Ah, sorry, I missed your reply. That works for me, thanks for the info.
